feat: nuxt module
blasdfaa/gravuety pull request #57
Opened 2024-09-04 12:52 UTC by brokuka

2024-09-04 16:15 UTC, blasdfaa requested changes

2024-09-04 16:15 UTC, blasdfaa commented on package.json
> +    "nuxt:dev": "pnpm --filter gravity-nuxt dev",
Запускать модуль в дев-режиме отсюда думаю не стоит, в этом нет особого смысла. Нужно добавить скрипт 
```json
"build:nuxt": "pnpm --filter nuxt build",
```

2024-09-04 16:15 UTC, blasdfaa commented on packages/module/package.json
> +  "name": "gravity-nuxt",
```suggestion
  "name": "@gravity-vue/nuxt",
```
Не забудь обновить везде где используется

2024-09-04 16:15 UTC, blasdfaa commented on packages/module/package.json
Папку с модулем лучше назвать просто "nuxt"

2024-09-04 16:15 UTC, blasdfaa commented on packages/module/package.json
> +  "scripts": {
Сюда нужен скрипт "build"

2024-09-04 16:15 UTC, blasdfaa commented on packages/module/src/module.ts
> +    configKey: 'gravityUI',
лучше так
```suggestion
    configKey: 'gravity',
```

2024-09-04 16:15 UTC, blasdfaa commented on packages/module/src/module.ts
> +    const PROVIDERS_DIR_PATH = resolve('../../gravity-vue/src/providers')
Проще во vue пакете добавить экспорт по типу `export * as components from './components'`, а не считывать файлы руками

2024-09-04 16:15 UTC, blasdfaa commented on packages/module/src/types.ts
> +    nuxtUI?: ModuleOptions
почему `nuxtUI`?

2024-09-04 18:28 UTC, brokuka commented on packages/module/src/types.ts
> +    nuxtUI?: ModuleOptions
хз, видимо в спешке :D

2024-09-08 17:48 UTC, blasdfaa approved these changes, later dismissed

2024-09-08 19:14 UTC, merged